src := yang.c model-cli.c
obj := $(src-o-files)
$(all-daemon)
$(cf-local)

tests_src := config_test.c
tests_targets := $(tests_targets) $(tests-target-files)
tests_objs := $(tests_objs) $(src-o-files)
